# Use official Golang image
FROM golang:latest

# Install Air for hot-reloading
RUN go install github.com/air-verse/air@latest

# Set working directory
WORKDIR /app

# Copy go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy rest of the files
COPY . .

EXPOSE 8080

# Run entrypoint script
CMD ["air"]
